version: '3'

services:

  cakephp:
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: cakephp_quickstart
    hostname: cakephp
    build:
      context: .
      dockerfile: ./docker/cakephp.dockerfile
    depends_on:
      - mysql
    volumes:
      - ./app:/app
    ports:
      - "8764:80"


  mysql:
    image: mysql:5.7
    container_name: db_quickstart
    hostname: mysql
    restart: unless-stopped
    volumes:
      - sqldata_quickstart:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_quickstart
    hostname: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    links:
      - mysql:db

volumes:
  sqldata_quickstart:
